#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:www-data" "$install_dir"
chmod -R o-rwx "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY (posts.json)
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"
chown "$app:www-data" "$data_dir"
chmod 750 "$data_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/php/$phpversion/fpm/pool.d/$app.conf"
ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RELOAD SERVICES
#=================================================
ynh_script_progression "Reloading NGINX and PHP-FPM..."

ynh_systemctl --service="php$phpversion-fpm" --action=reload
ynh_systemctl --service=nginx                --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
